/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { be_ } from '@ctx-core/object'
import type { flash_Ctx } from './flash_Ctx'
import type { flash$_T } from './flash$_b'
import { flash$_b } from './flash$_b'
import type { flash_error$_T } from './flash_error$_b'
import { flash_error$_b } from './flash_error$_b'
import type { flash_expire_timeout_id$_T } from './flash_expire_timeout_id$_b'
import { flash_expire_timeout_id$_b } from './flash_expire_timeout_id$_b'
import type { flash_message$_T } from './flash_message$_b'
import { flash_message$_b } from './flash_message$_b'
import type { flash_queue$_T } from './flash_queue$_b'
import { flash_queue$_b } from './flash_queue$_b'
export interface flash_ctx_I {
	flash$?:flash$_T
	flash_error$?:flash_error$_T
	flash_expire_timeout_id$?:flash_expire_timeout_id$_T
	flash_message$?:flash_message$_T
	flash_queue$?:flash_queue$_T
	flash_b_h?:flash_b_h_T
}
export interface flash_b_h_T {
	get flash$():flash$_T
	get flash_error$():flash_error$_T
	get flash_expire_timeout_id$():flash_expire_timeout_id$_T
	get flash_message$():flash_message$_T
	get flash_queue$():flash_queue$_T
}
export function flash_b_h_b(ctx:flash_Ctx):flash_b_h_T {
	return be_<flash_Ctx, 'flash_b_h'>('flash_b_h', ()=>{
		return {
			get flash$() { return flash$_b(ctx) },
			get flash_error$() { return flash_error$_b(ctx) },
			get flash_expire_timeout_id$() { return flash_expire_timeout_id$_b(ctx) },
			get flash_message$() { return flash_message$_b(ctx) },
			get flash_queue$() { return flash_queue$_b(ctx) }
		}
	})(ctx)
}
