/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { flash$_T } from './flash$_b.js'
import type { flash_error$_T } from './flash_error$_b.js'
import type { flash_expire_timeout_id$_T } from './flash_expire_timeout_id$_b.js'
import type { flash_message$_T } from './flash_message$_b.js'
import type { flash_queue$_T } from './flash_queue$_b.js'
export interface flash_ctx_I {
	flash$?:flash$_T
	flash_error$?:flash_error$_T
	flash_expire_timeout_id$?:flash_expire_timeout_id$_T
	flash_message$?:flash_message$_T
	flash_queue$?:flash_queue$_T
}